classDiagram

class Library{
    +add_book()
    +register_user()
    +create_loan()
}

class Book{
    +str title
    +str author
    +bool state
    +mark_as_unavailable()
    +mark_as_available()
}

Library "1" o-- "0.." Book

class User{
    +str name
    +str email
}

Library "1" --> "0.." User

class Loan{
    +str start_date
    +str end_date
    +close_loan()
}
Loan "0.." --> "1" Book

Loan "0.." --> "1" User

Library "1" -- "0.." Loan
